In [4]:
import torch
print(torch.__version__)

scalar = torch.tensor(7)
scalar

2.5.1+cu124


tensor(7)

In [5]:
vector = torch.tensor([7, 7])
vector.ndim

1

In [6]:
vector.shape 

torch.Size([2])

In [7]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

print("ndim:", MATRIX.ndim)
print("shape:", MATRIX.shape)

ndim: 2
shape: torch.Size([2, 2])


In [8]:
TENSOR = torch.tensor([[[1, 2, 3],
						[4, 5, 6],
						[7 , 8, 9]],
					   [[10, 11, 12],
					    [13, 14, 15],
					    [16, 17, 18]]])
#  There are 2, 3x3 matrices.


print("ndim:", TENSOR.ndim)
print("shape:", TENSOR.shape)

ndim: 3
shape: torch.Size([2, 3, 3])


## There are 2, 3x3 matrices.

In [9]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4513, 0.2552, 0.7375, 0.5059],
         [0.8771, 0.7874, 0.3412, 0.5370],
         [0.7855, 0.7360, 0.2106, 0.3712]]),
 torch.float32)

In [10]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
# prints: (torch.Size([224, 224, 3]), 3)

(torch.Size([224, 224, 3]), 3)

In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [12]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Basic Operations

In [13]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10
# Prints out tensor([11, 12, 13])

# Multiply it by 10
tensor * 10
# Prints out tensor([10, 20, 30)

tensor([10, 20, 30])

In [14]:
# Tensors don't change unless reassigned
tensor
# Prints out tensor([1, 2, 3])

tensor([1, 2, 3])

In [15]:
tensor = tensor - 10
tensor
# Prints out tensor([-9, -8, -7])

# Add and reassign
tensor = tensor + 10
tensor
# Prints out tensor([1, 2, 3])

tensor([1, 2, 3])

In [16]:
# Can also use torch functions
torch.multiply(tensor, 10)
# tensor([10, 20, 30])

tensor([10, 20, 30])

In [17]:
# Original tensor is still unchanged 
tensor
# Prints out tensor([1, 2, 3])

tensor([1, 2, 3])

In [18]:
tensor = torch.tensor([1, 2, 3])
tensor.shape
# Prints torch.Size([3])

torch.Size([3])

In [19]:
tensor * tensor
# tensor([1, 4, 9])

# Matrix multiplication
torch.matmul(tensor, tensor)
# tensor(14)

# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor
# tensor(14)

tensor(14)

# Shape Errors

In [20]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)
# tensor([[1., 2.],
#        [3., 4.],
#        [5., 6.]])
# tensor([[ 7., 10.],
#        [ 8., 11.],
#        [ 9., 12.]])

# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)
#tensor([[1., 2.],
#        [3., 4.],
#        [5., 6.]])
#tensor([[ 7.,  8.,  9.],
#        [10., 11., 12.]])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

# Input shape: torch.Size([3, 2])
# 
# Output:
# tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
#         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
#         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
#        grad_fn=<AddmmBackward0>)
# 
# Output shape: torch.Size([3, 6])

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#  Finding the min, max, mean, sum, etc (aggregation)

In [21]:
# Create a tensor
x = torch.arange(0, 100, 10)
x
# tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)
# (tensor(90), tensor(0), tensor(45.), tensor(450))

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [24]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [25]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype
# torch.float32

torch.float32

In [26]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16
# tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [27]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8
# tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, Stacking, Squeezing and Unsequeezing

In [28]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape
# (tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [29]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [30]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [31]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [32]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [33]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [34]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [35]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing

In [48]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [54]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"First square bracket:\n{x[0][0]}")
print(f"First square bracket:\n{x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
First square bracket:
tensor([1, 2, 3])
First square bracket:
1


# PyTorch Tensors & Numpy

In [55]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# Reproducibility

In [56]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2537, 0.9792, 0.1264, 0.7522],
        [0.7563, 0.0833, 0.4062, 0.5181],
        [0.5201, 0.9497, 0.5072, 0.8215]])

Tensor B:
tensor([[4.3399e-01, 5.0353e-01, 3.4575e-01, 1.4584e-01],
        [5.2655e-01, 1.5510e-01, 6.1875e-01, 5.4529e-01],
        [2.7168e-01, 3.9176e-01, 3.0994e-05, 7.8580e-01]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [62]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPU

In [63]:
torch.cuda.is_available()

True

In [64]:
torch.cuda.device_count()

1

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [65]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')