In [1]:
import torch


# 2. Create a random tensor with shape (7, 7)

In [3]:
random_tensor = torch.rand(size=(7, 7))
print("2. Create a random tensor with shape (7, 7):")
random_tensor

2. Create a random tensor with shape (7, 7):


tensor([[0.8976, 0.7835, 0.6937, 0.9836, 0.4776, 0.8437, 0.1984],
        [0.4442, 0.4661, 0.0686, 0.9301, 0.1283, 0.2479, 0.3712],
        [0.5621, 0.5055, 0.3313, 0.0225, 0.4196, 0.7056, 0.4139],
        [0.4220, 0.6600, 0.9272, 0.2629, 0.6898, 0.8807, 0.6136],
        [0.4412, 0.8994, 0.9686, 0.4323, 0.0961, 0.4956, 0.4562],
        [0.0403, 0.8488, 0.0725, 0.0752, 0.2495, 0.3116, 0.5788],
        [0.6501, 0.3244, 0.6778, 0.5236, 0.7446, 0.4411, 0.8892]])

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7). (hint: you may have to transpose the second tensor).


In [37]:
random_tensor_2 = torch.rand(size=(1, 7))

# create a transpose of randem_tensor_2
random_tensor_2_transposed = random_tensor_2.T

# make matrix multiplication
multiplicated_tensor = random_tensor.matmul(random_tensor_2_transposed)
multiplicated_tensor

tensor([[2.4733],
        [1.4590],
        [1.3522],
        [1.9654],
        [1.7064],
        [0.8488],
        [1.8026]])

# 4. Set the random seed to 0 and do exercises 2 & 3 over again

In [223]:
import random, time

time_cpu_start = time.time()

RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
random_tensor_seed = torch.rand(size=(7, 7))
random_tensor_seed_2 = torch.rand(size=(1, 7))

random_tensor_seed_2_transposed = random_tensor_seed_2.T
multiplicated_tensor_seed = random_tensor_seed.matmul(random_tensor_seed_2_transposed)

time_cpu_end = time.time()

measured_time = time_cpu_end - time_cpu_start
print("measured_time_cpu: ", measured_time)

measured_time_cpu:  0.0008149147033691406


# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

https://pytorch.org/docs/main/notes/cuda.html

In [180]:
cuda = torch.device('cuda:0')

with cuda:
    time_gpu_start = time.time()
    
    GPU_SEED = 1234
    torch.manual_seed(GPU_SEED)

    x = torch.rand(size=(7, 7))
    y = torch.rand(size=(1, 7))

    y_transposed = y.T
    mult = x.matmul(y_transposed)
    
    time_gpu_end = time.time()

    print("measured_time_gpu: ", time_gpu_end - time_gpu_start)
    
    print(mult)

measured_time_gpu:  0.0008294582366943359
tensor([[0.9558],
        [1.2227],
        [0.9335],
        [1.6030],
        [0.9344],
        [0.5282],
        [0.5664]], device='cuda:0')


# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
torch.manual_seed(1234)

a = torch.rand(size=(2, 3))
b = torch.rand(size=(2, 3))

a_gpu = a.cuda()
b_gpu = b.cuda()

print("a_gpu:")
print(a_gpu)
print("b_gpu:")
print(b_gpu)



a_gpu:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
b_gpu:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [232]:
b_gpu_transposed = b_gpu.T

ab_mult = a_gpu.matmul(b_gpu_transposed)
ab_mult

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

# 8. Find the maximum and minimum values of the output of 7.


In [234]:
ab_mult_max = ab_mult.max()
ab_mult_min = ab_mult.min()

print("ab_mult_max:")
print(ab_mult_max)
print("ab_mult_min:")
print(ab_mult_min)

ab_mult_max:
tensor(0.5617, device='cuda:0')
ab_mult_min:
tensor(0.3647, device='cuda:0')


# 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
ab_mult_ind_max = ab_mult[-1][-1]  # Take the last value
ab_mult_ind_min = ab_mult[0][0]

print("ab_mult_ind_max:")
print(ab_mult_ind_max)
print("ab_mult_ind_min:")
print(ab_mult_ind_min)

ab_mult_ind_max:
tensor(0.5617, device='cuda:0')
ab_mult_ind_min:
tensor(0.3647, device='cuda:0')


# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [253]:
torch.manual_seed(7)
shaped_tensor = torch.rand(size=(1, 1, 1, 10))
print("shaped_tensor (1, 1, 1, 10):")
print(shaped_tensor)
print("shape:", shaped_tensor.shape)

squeezed_tensor = shaped_tensor.squeeze()
print("\nsqueezed_tensor (1, 1, 1, 10):")
print(squeezed_tensor)
print("shape:", squeezed_tensor.shape)



shaped_tensor (1, 1, 1, 10):
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
shape: torch.Size([1, 1, 1, 10])

squeezed_tensor (1, 1, 1, 10):
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
shape: torch.Size([10])
