In [15]:
import torch
print(torch.__version__)

scalar = torch.tensor(7)
scalar

2.5.1+cu124


tensor(7)

In [17]:
vector = torch.tensor([7, 7])
vector.ndim

1

In [18]:
vector.shape 

torch.Size([2])

In [23]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

print("ndim:", MATRIX.ndim)
print("shape:", MATRIX.shape)

ndim: 2
shape: torch.Size([2, 2])


In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
						[4, 5, 6],
						[7 , 8, 9]],
					   [[10, 11, 12],
					    [13, 14, 15],
					    [16, 17, 18]]])
#  There are 2, 3x3 matrices.


print("ndim:", TENSOR.ndim)
print("shape:", TENSOR.shape)

ndim: 3
shape: torch.Size([2, 3, 3])


## There are 2, 3x3 matrices.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3740, 0.7851, 0.3315, 0.1693],
         [0.2912, 0.5935, 0.5180, 0.2071],
         [0.0405, 0.7410, 0.1387, 0.2520]]),
 torch.float32)

In [28]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
# prints: (torch.Size([224, 224, 3]), 3)

(torch.Size([224, 224, 3]), 3)

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [30]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])