In [2]:
import torch
print(torch.__version__)

scalar = torch.tensor(7)
scalar

2.5.1+cu124


tensor(7)

In [3]:
vector = torch.tensor([7, 7])
vector.ndim

1

In [4]:
vector.shape 

torch.Size([2])

In [5]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

print("ndim:", MATRIX.ndim)
print("shape:", MATRIX.shape)

ndim: 2
shape: torch.Size([2, 2])


In [6]:
TENSOR = torch.tensor([[[1, 2, 3],
						[4, 5, 6],
						[7 , 8, 9]],
					   [[10, 11, 12],
					    [13, 14, 15],
					    [16, 17, 18]]])
#  There are 2, 3x3 matrices.


print("ndim:", TENSOR.ndim)
print("shape:", TENSOR.shape)

ndim: 3
shape: torch.Size([2, 3, 3])


## There are 2, 3x3 matrices.

In [7]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0293, 0.3378, 0.7046, 0.5070],
         [0.6458, 0.7026, 0.1855, 0.2296],
         [0.7382, 0.3094, 0.4717, 0.9350]]),
 torch.float32)

In [8]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
# prints: (torch.Size([224, 224, 3]), 3)

(torch.Size([224, 224, 3]), 3)

In [9]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [10]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Basic Operations

In [11]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10
# Prints out tensor([11, 12, 13])

# Multiply it by 10
tensor * 10
# Prints out tensor([10, 20, 30)

tensor([10, 20, 30])

In [12]:
# Tensors don't change unless reassigned
tensor
# Prints out tensor([1, 2, 3])

tensor([1, 2, 3])

In [13]:
tensor = tensor - 10
tensor
# Prints out tensor([-9, -8, -7])

# Add and reassign
tensor = tensor + 10
tensor
# Prints out tensor([1, 2, 3])

tensor([1, 2, 3])

In [14]:
# Can also use torch functions
torch.multiply(tensor, 10)
# tensor([10, 20, 30])

tensor([10, 20, 30])

In [15]:
# Original tensor is still unchanged 
tensor
# Prints out tensor([1, 2, 3])

tensor([1, 2, 3])

In [16]:
tensor = torch.tensor([1, 2, 3])
tensor.shape
# Prints torch.Size([3])

torch.Size([3])

In [18]:
tensor * tensor
# tensor([1, 4, 9])

# Matrix multiplication
torch.matmul(tensor, tensor)
# tensor(14)

# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor
# tensor(14)

tensor(14)

# Shape Errors

In [19]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [20]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)
# tensor([[1., 2.],
#        [3., 4.],
#        [5., 6.]])
# tensor([[ 7., 10.],
#        [ 8., 11.],
#        [ 9., 12.]])

# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)
#tensor([[1., 2.],
#        [3., 4.],
#        [5., 6.]])
#tensor([[ 7.,  8.,  9.],
#        [10., 11., 12.]])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

# Input shape: torch.Size([3, 2])
# 
# Output:
# tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
#         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
#         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
#        grad_fn=<AddmmBackward0>)
# 
# Output shape: torch.Size([3, 6])

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
